Tensors are similar to Numpy's ndarrays. 
Uninitialized matrix is declared but does not contain definite known values before it is used.





In [1]:
import torch

#Constructing a matrix of order mxn, uninitialized.
x = torch.empty(6,5)
print(x)

tensor([[3.5317e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [2]:
#Constructing a matrix randomly initialized.
x = torch.rand(6,5)
print(x)

tensor([[0.2162, 0.6019, 0.1757, 0.1965, 0.5305],
        [0.7411, 0.3765, 0.2684, 0.2127, 0.1437],
        [0.3313, 0.9496, 0.7258, 0.5029, 0.1901],
        [0.1776, 0.3593, 0.7484, 0.1236, 0.2288],
        [0.9775, 0.4358, 0.7087, 0.3738, 0.1065],
        [0.4006, 0.7823, 0.7352, 0.5879, 0.4513]])


In [3]:
#Contruct a matrix filled with zero & datatype long
x = torch.zeros(6, 5, dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


In [4]:
#Constructing tensor directly from data
x = torch.tensor([10.5, 3.4, 4.6])
print(x)

tensor([10.5000,  3.4000,  4.6000])


In [5]:
#Create a tensor based on existing tensor. You can reuse the properties of input tensor.  
x = x.new_ones(6,5, dtype=torch.double)
print(x)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [6]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.6180,  0.2536,  0.6509,  0.4358,  0.8177],
        [-0.5990, -1.0919, -0.4271,  0.0857,  0.0023],
        [-0.6118, -2.0209,  0.7929,  1.4457,  0.1176],
        [-0.1298,  1.1472,  0.3096,  0.8403,  0.5898],
        [ 1.1666, -0.1350,  0.8701,  0.6788, -0.5345],
        [ 0.2639,  2.3124, -1.4526,  0.9784,  0.0656]])


In [7]:
#Getting size of the tensor

print(x.size())

torch.Size([6, 5])


Operations on Tensors

In [8]:
#Addition Operation with different syntax
x = torch.rand(3,4)
y = torch.rand(3,4)
print('\n\n--------------- X ---------------\n')
print(x)
print('\n\n--------------- Y ---------------\n')
print(y)
print('\n\n================== X+Y ==================\n')
print(x+y)
print('\n\n================== Using add() ==================\n')
print(torch.add(x,y))
print('\n\n======= Using add() with output tensor, torch.add(x, y, out=res) =========\n')
res = torch.empty(3,4)
torch.add(x, y, out=res)
print(res)
print('\nWe can also assign the output tensor as z = x+y \n')
z = x+y
print(z)
print('\n\nOR with z = torch.add(x,y) \n')
z = torch.add(x,y)
print(z)



--------------- X ---------------

tensor([[0.4396, 0.1578, 0.2179, 0.8788],
        [0.9716, 0.8128, 0.7529, 0.4552],
        [0.0609, 0.9898, 0.2517, 0.8867]])


--------------- Y ---------------

tensor([[0.2309, 0.2512, 0.6185, 0.2961],
        [0.1938, 0.1654, 0.1985, 0.6581],
        [0.0352, 0.7509, 0.5288, 0.1502]])


================== X+Y ==================

tensor([[0.6704, 0.4090, 0.8364, 1.1749],
        [1.1654, 0.9783, 0.9514, 1.1133],
        [0.0961, 1.7407, 0.7805, 1.0369]])


================== Using add() ==================

tensor([[0.6704, 0.4090, 0.8364, 1.1749],
        [1.1654, 0.9783, 0.9514, 1.1133],
        [0.0961, 1.7407, 0.7805, 1.0369]])


======= Using add() with output tensor, torch.add(x, y, out=res) =========

tensor([[0.6704, 0.4090, 0.8364, 1.1749],
        [1.1654, 0.9783, 0.9514, 1.1133],
        [0.0961, 1.7407, 0.7805, 1.0369]])

We can also assign the output tensor as z = x+y 

tensor([[0.6704, 0.4090, 0.8364, 1.1749],
        [1.1654, 0.978

In [9]:
#inplace addition using *_.
#Any operation that mutates tensor will be post-fixed with an _
print('\n\n*********** In-place addition ***********')
print('\n -------- Y(Before) ------------\n')
print(y)
y.add_(x)
print('\n\n -------- Y(After) ----------\n')
print(y)



*********** In-place addition ***********

 -------- Y(Before) ------------

tensor([[0.2309, 0.2512, 0.6185, 0.2961],
        [0.1938, 0.1654, 0.1985, 0.6581],
        [0.0352, 0.7509, 0.5288, 0.1502]])


 -------- Y(After) ----------

tensor([[0.6704, 0.4090, 0.8364, 1.1749],
        [1.1654, 0.9783, 0.9514, 1.1133],
        [0.0961, 1.7407, 0.7805, 1.0369]])


Converting a Torch array to Numpy array


In [24]:
a = torch.randn(5)
print("\nTensor : ", a)

b = a.numpy()
print("\nNumpy array : ", b)

#Both a and b share their memory locations, and hence modifying one will change the other.
#(when torch tensor is on CPU) 

a.add_(1)
print('\n', a)
print('\n', b)



Tensor :  tensor([-0.7484,  1.0297, -0.3599, -1.2823,  0.5395])

Numpy array :  [-0.7483857   1.029721   -0.35990942 -1.2823412   0.53953546]

 tensor([ 0.2516,  2.0297,  0.6401, -0.2823,  1.5395])

 [ 0.25161427  2.029721    0.6400906  -0.28234124  1.5395355 ]


Converting a Numpy array to Torch array

In [23]:
import numpy as np

a = np.arange(5)
print('\nNumpy array : ', a)

b = torch.from_numpy(a)
print('\nTensor array : ', b)

np.add(a, 2, out=a)
print('\n', a)
print('\n', b)


Numpy array :  [0 1 2 3 4]

Tensor array :  tensor([0, 1, 2, 3, 4])

 [2 3 4 5 6]

 tensor([2, 3, 4, 5, 6])
