Automatic Differentiation

For all operations on Tensors, automatic differentiation is provided by autograd package.

When we set the attribute ***.requires_grad*** as True, all the operations on Tensors will be tracked. The gradient for the tensor will be accumulated into ***.grad*** attribute.

To prevent the computation history from being tracked call ***.detach()*** on the tensor.

Calling ***.backward()*** on a Tensor will compute the derivatives. 
When Tensor is scalar(holds one element data), then backward() does not need any arguments.
If it has more elements, we need to provide a gradient argument, i.e a tensor of matching shape. 

Let's begin to code....

In [2]:
import torch

x = torch.randn(4,3, requires_grad=True)
print('\n----------- x ------------')
print(x)


----------- x ------------
tensor([[ 1.2012,  1.7958,  0.4781],
        [-0.2387,  1.3726, -0.0301],
        [ 1.1328,  0.9182, -0.5147],
        [ 0.8763, -0.2810,  0.2551]], requires_grad=True)


In [3]:
y = x + 1
print('\n----------- y ------------')
print(y)



----------- y ------------
tensor([[2.2012, 2.7958, 1.4781],
        [0.7613, 2.3726, 0.9699],
        [2.1328, 1.9182, 0.4853],
        [1.8763, 0.7190, 1.2551]], grad_fn=<AddBackward0>)


In [5]:
#As y was a result of an operation on Tensor x with requires_grad, 
#it will have a grad_fn attribute.
print(y.grad_fn)

In [9]:
z = y + y + 2
print('\n----------- z ------------')
print(z)

#Get the mean() of z.
m = z.mean()
print('\nMean of z : ', m)



----------- z ------------
tensor([[6.4025, 7.5917, 4.9562],
        [3.5226, 6.7452, 3.9398],
        [6.2656, 5.8364, 2.9707],
        [5.7526, 3.4381, 4.5101]], grad_fn=<AddBackward0>)

Mean of z :  tensor(5.1610, grad_fn=<MeanBackward0>)


In [13]:
#Computing the derivatives
m.backward()

#Print gradients d(m)/dx
print(x.grad)

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
