Deep Dive into **Torch package** 

Reference: PyTorch Documentation

torch package has datastructures for multi-dimensional tensors.



**Construct a Tensor with data**

Use torch.tensor(data)

Note: torch.tensor() copies data always.


In [0]:
import torch

In [0]:
torch.tensor([]) #Creates an empty tensor

tensor([])

In [0]:
#Create a tensor with some data.
#Note : tensor object infers the datatype of values in given data. 
#Let's use data with float type 
torch.tensor([[0.5, 0.3, 0.6], [1.2, 1.4, 1.6], [2.1, 2.3, 2.5]])

tensor([[0.5000, 0.3000, 0.6000],
        [1.2000, 1.4000, 1.6000],
        [2.1000, 2.3000, 2.5000]])

In [0]:
#Let's use data with int type 
torch.tensor([[5, 3, 6], [2, 4, 6], [1, 3, 5]])

tensor([[5, 3, 6],
        [2, 4, 6],
        [1, 3, 5]])

In [0]:
#What happens if we use mixture of both float and int?
torch.tensor([[1, 2, 3], [1.1, 2.1, 3.1]])
torch.tensor([[1.1, 2.1, 3.1], [1, 2, 3]])

tensor([[1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000]])

In [0]:
#Creating a zero-dimensional tensor. 
torch.tensor(4.1234)

tensor(4.1234)

In [0]:
#Specifying the datatype while creating a tensor
torch.tensor([[0.5, 0.3, 0.6], [1.2, 1.4, 1.6], [2.1, 2.3, 2.5]], 
             dtype=torch.float64)

tensor([[0.5000, 0.3000, 0.6000],
        [1.2000, 1.4000, 1.6000],
        [2.1000, 2.3000, 2.5000]], dtype=torch.float64)

Converting existing data into Tensor

Existing data can be list, tuple, NumPy ndarray, scalar

Use **as_tensor**() 

Note that as_tensor() avoids copying the data if original data is a numpy array.

In [0]:
#Converting list to Tensor
x = [2, 4, 6, 8]
y = torch.as_tensor(x)

print(y)

#Now modify 'y'
y[1] = 10

print('y : ', y)
print('x : ', x)
print("\ny changed, but x did not..")

tensor([2, 4, 6, 8])
y :  tensor([ 2, 10,  6,  8])
x :  [2, 4, 6, 8]

y changed, but x did not..


In [0]:
#Let's try with ndarray to Tensor
import numpy as np
x = np.array([2, 4, 6, 8])
y = torch.as_tensor(x)
print(y)

#Now let's modify y
y[1] = 10

print('y : ', y)
print('x : ', x)

print("\ny changed, and x also did..!")

tensor([2, 4, 6, 8])
y :  tensor([ 2, 10,  6,  8])
x :  [ 2 10  6  8]

y changed, and x also did..!


Creating a view from existing tensor.

Use: **as_strided()**

Many PyTorch functions which return the view of a tensor are internally implemented with this function.


In [0]:
#Create a Tensor
x = torch.tensor([[1.2, 3.2, 4.2], [2.4, 3.4, 4.4], [6.5, 3.2, 1.2]])
print('\n', x)

t = torch.as_strided(x, (2,2), (1,2))
print('\n',t)




 tensor([[1.2000, 3.2000, 4.2000],
        [2.4000, 3.4000, 4.4000],
        [6.5000, 3.2000, 1.2000]])

 tensor([[1.2000, 4.2000],
        [3.2000, 2.4000]])


Creating a Tensor from Numpy Array

Use: **from_numpy()**

Modifications to Numpy Array will reflect in Tensor and vice versa. 

The returned Tensor is not resizable.

In [0]:
import numpy as np
x = torch.from_numpy(np.array([2, 4, 6, 8, 10]))

x

tensor([ 2,  4,  6,  8, 10])

Creating Tensor filled with '0'.

Use: **zeros()**


In [0]:
x = torch.zeros(2,4)

x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
x = torch.zeros(10)

x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Creating Tensor filled with zero, using the shape of an existing tensor.

Use: **zeros_like()**

In [0]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('\n------------- X -------------\n', x)

y = torch.zeros_like(x)
print('\n------------- Y -------------\n', y)


------------- X -------------
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

------------- Y -------------
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Creating Tensor filled with '1'

Use: **ones()**

In [0]:
x = torch.ones(3, 4)

x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Creating Tensor filled with one, using the shape of an existing tensor.

Use: **ones_like()**

In [0]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('\n------------- X -------------\n', x)

y = torch.ones_like(x)

print('\n------------- Y -------------\n', y)


------------- X -------------
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

------------- Y -------------
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


Creating 1D Tensor with values ranging from given 'begin' to 'end'. 

Use: **arange()**

In [0]:
#When only one value is mentioned, always starts with 0 and ends at given value - 1.
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [0]:
#Now let's give both begin and end
x = torch.arange(2, 6)
x

tensor([2, 3, 4, 5])

In [0]:
#In both the cases, values had incremented by 1. Now let's try by giving a 'step'
x = torch.arange(1, 10, 0.5)
x

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

Create a 1D Tensor of steps of equally spaced points between given 'begin' and 'end'

Use: **linspace()**

If steps are not mentioned default 100 will be considered.

In [0]:
#0:begin, 5:end and 3:steps
x = torch.linspace(0, 5, 3)
x

tensor([0.0000, 2.5000, 5.0000])

In [0]:
x = torch.linspace(0, 5)
x

tensor([0.0000, 0.0505, 0.1010, 0.1515, 0.2020, 0.2525, 0.3030, 0.3535, 0.4040,
        0.4545, 0.5051, 0.5556, 0.6061, 0.6566, 0.7071, 0.7576, 0.8081, 0.8586,
        0.9091, 0.9596, 1.0101, 1.0606, 1.1111, 1.1616, 1.2121, 1.2626, 1.3131,
        1.3636, 1.4141, 1.4646, 1.5152, 1.5657, 1.6162, 1.6667, 1.7172, 1.7677,
        1.8182, 1.8687, 1.9192, 1.9697, 2.0202, 2.0707, 2.1212, 2.1717, 2.2222,
        2.2727, 2.3232, 2.3737, 2.4242, 2.4747, 2.5253, 2.5758, 2.6263, 2.6768,
        2.7273, 2.7778, 2.8283, 2.8788, 2.9293, 2.9798, 3.0303, 3.0808, 3.1313,
        3.1818, 3.2323, 3.2828, 3.3333, 3.3838, 3.4343, 3.4848, 3.5354, 3.5859,
        3.6364, 3.6869, 3.7374, 3.7879, 3.8384, 3.8889, 3.9394, 3.9899, 4.0404,
        4.0909, 4.1414, 4.1919, 4.2424, 4.2929, 4.3434, 4.3939, 4.4444, 4.4949,
        4.5455, 4.5960, 4.6465, 4.6970, 4.7475, 4.7980, 4.8485, 4.8990, 4.9495,
        5.0000])

In [0]:
x.shape

torch.Size([100])

In [0]:
x = torch.linspace(-5, 5, 5)
x

tensor([-5.0000, -2.5000,  0.0000,  2.5000,  5.0000])

In [0]:
#If steps are set to 1, it would return a tensor with 'begin' value
x = torch.linspace(-5, 5, 1)
x

tensor([-5.])

Creating a Tensor of steps points logarithmically spaced with base, between base_start and base_end.

Use: **logspace()**

If steps are not mentioned default 100 will be considered.

If base is not given, default 10 will be considered.


In [0]:
# 0.2 begin, 0.8 end and 5 steps
x = torch.logspace(0.2, 0.8, 5)
x

tensor([1.5849, 2.2387, 3.1623, 4.4668, 6.3096])

In [0]:
# 0.2 begin, 0.8 end, 4 steps and values with base 2
x = torch.logspace(0.2, 0.8, 4, 2)
x

tensor([1.1487, 1.3195, 1.5157, 1.7411])

In [0]:
#If steps are set to 1, it would NOT return a tensor with 'begin' value, 
#but a tensor with base_begin, for given base. If base not given default 10.

# 0.2 begin, 0.8 end, 1 step and values with base 2
x = torch.logspace(0.2, 0.8, 1, 2)
x

tensor([1.1487])

Creating an Indentity Matrix like tensor
(1 in diagonal and 0 elsewhere)

Use: **eye()**


In [0]:
x = torch.eye(5) #creates a tensor of 5x5 
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [0]:
#What happens when number of rows and columns do not match? Let's see...
x = torch.eye(4,6)
x


tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]])

Creating a tensor filled with uninitialized data. 

Use: **empty()** 

Like *zeros_like()* and *ones_like()*, we can use *empty_like()* by giving existing input tensor. 
It is equivalent to *empty()*


In [0]:
#(2,2) defines the size of tensor
x = torch.empty(2, 2)
x

tensor([[1.0717e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

Creating a tensor of given size, filled with a value.

Use: **full()**

Like *empty_like()*, we can use *full_like()* by giving existing input tensor. It is equivalent to *full()*

In [0]:
#3 rows, 4 columns and filled with 2.15
x = torch.full((3,4), 2.15)
x

tensor([[2.1500, 2.1500, 2.1500, 2.1500],
        [2.1500, 2.1500, 2.1500, 2.1500],
        [2.1500, 2.1500, 2.1500, 2.1500]])

In [0]:
y = torch.full_like(x, 3.6)
y

tensor([[3.6000, 3.6000, 3.6000, 3.6000],
        [3.6000, 3.6000, 3.6000, 3.6000],
        [3.6000, 3.6000, 3.6000, 3.6000]])

Converting a float tensor to a quantized tensor with given scale and zero point.

*scale(float)*: scale to apply in quantization formula.

*zero_point(int)*: offset in integer value that maps to float zero.

Use: **quantize_per_tensor()**

In [0]:
x = torch.tensor([0.2, 0.6, 1.2, -1.7])
print('---------- x ----------\n', x)

# 0.1 scale, 10 zero_point
y = torch.quantize_per_tensor(x, 0.1, 10, torch.qint8)
print('\n---------- y ----------\n', y)

---------- x ----------
 tensor([ 0.2000,  0.6000,  1.2000, -1.7000])

---------- y ----------
 tensor([ 0.2000,  0.6000,  1.2000, -1.7000], size=(4,), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)


What is the difference between x and y...! The values look same..! Let's see the underlying integer representation. 

Use: **int_repr()**

In [0]:
print('---------- y - int_representation ----------\n\n', y.int_repr())

---------- y - int_representation ----------

 tensor([12, 16, 22, -7], dtype=torch.int8)


In [0]:
#What happens if we use int_repr() on input float tensor x. That's an ERROR.... Bhoooooom...!
print(x.int_repr())

RuntimeError: ignored

Converting a float tensor 'X', to per-channel quantized tensor with scales and zero points.

scales(tensor): float 1D tensor of scales

zero_points(tensor): 1D tensor of offsets

axis(int): dimension on which to apply per-channel quantization.

The size of scales and zero points should match input.size(axis), where input is the float tensor 'X'

Use: **quantize_per_channel()**

In [0]:
x = torch.tensor([[1.2, -2.1, 3.5], [0.4, -1.3, -1.1]])
print('---------- x ----------\n', x)

y = torch.quantize_per_channel(x, torch.tensor([0.1, 0.01]), torch.tensor([10, 0]), 0, torch.quint8)
print('\n---------- y ----------\n', y)
print('\n\n---------- y - int_representation ----------\n\n', y.int_repr())

---------- x ----------
 tensor([[ 1.2000, -2.1000,  3.5000],
        [ 0.4000, -1.3000, -1.1000]])

---------- y ----------
 tensor([[ 1.2000, -1.0000,  3.5000],
        [ 0.4000,  0.0000,  0.0000]], size=(2, 3), dtype=torch.quint8,
       quantization_scheme=torch.per_channel_affine,
       scale=tensor([0.1000, 0.0100], dtype=torch.float64),
       zero_point=tensor([10,  0]), axis=0)


---------- y - int_representation ----------

 tensor([[22,  0, 45],
        [40,  0,  0]], dtype=torch.uint8)


Concatenating Tensors

Use: **cat()**

All the tensors must have same shape or be empty.

In [0]:
x = torch.randn(3,4)
y = torch.randn(3,4)
print('\n------ x --------\n',x)
print('\n------ y --------\n',y)

#dimension over which tensors are concatenated = 0
z = torch.cat((x, y), 0)
print('\n------ z --------\n',z)

#dimension over which tensors are concatenated = 1
w = torch.cat((x, y), 1)
print('\n------ w --------\n',w)



------ x --------
 tensor([[ 0.2327,  0.2903, -1.3590, -1.0710],
        [ 0.4885, -0.6078,  0.5237, -0.2790],
        [-0.8863, -0.8613, -0.4970,  1.3279]])

------ y --------
 tensor([[ 0.0597, -0.6440,  0.3208,  0.4791],
        [ 0.1702, -0.7863,  0.0156,  1.0186],
        [-0.6583,  0.3036,  1.5650,  1.1892]])

------ z --------
 tensor([[ 0.2327,  0.2903, -1.3590, -1.0710],
        [ 0.4885, -0.6078,  0.5237, -0.2790],
        [-0.8863, -0.8613, -0.4970,  1.3279],
        [ 0.0597, -0.6440,  0.3208,  0.4791],
        [ 0.1702, -0.7863,  0.0156,  1.0186],
        [-0.6583,  0.3036,  1.5650,  1.1892]])

------ w --------
 tensor([[ 0.2327,  0.2903, -1.3590, -1.0710,  0.0597, -0.6440,  0.3208,  0.4791],
        [ 0.4885, -0.6078,  0.5237, -0.2790,  0.1702, -0.7863,  0.0156,  1.0186],
        [-0.8863, -0.8613, -0.4970,  1.3279, -0.6583,  0.3036,  1.5650,  1.1892]])


Splitting a tensor into specific number of chunks.

Use: **chunk()**
The last chunk will be smaller if the tensor size is not divisible by chunks.

In [0]:
x = torch.randn(3,4)
print('\n------ x --------\n',x)

#no. of chunks=2, dimension=1
y = torch.chunk(x, 2, 1)
print('\n------ y --------\n',y)

#no. of chunks=2, dimension=0
z = torch.chunk(x, 2, 0)
print('\n------ z --------\n',z)


------ x --------
 tensor([[ 1.0059,  1.1799,  0.1138, -0.2968],
        [-0.4073,  0.0742,  0.8377,  0.2526],
        [-0.8426,  0.6544, -0.0249, -1.4642]])

------ y --------
 (tensor([[ 1.0059,  1.1799],
        [-0.4073,  0.0742],
        [-0.8426,  0.6544]]), tensor([[ 0.1138, -0.2968],
        [ 0.8377,  0.2526],
        [-0.0249, -1.4642]]))

------ z --------
 (tensor([[ 1.0059,  1.1799,  0.1138, -0.2968],
        [-0.4073,  0.0742,  0.8377,  0.2526]]), tensor([[-0.8426,  0.6544, -0.0249, -1.4642]]))


Indexing the input tensor along dimension 'dim', using a 1D tensor of indices to index.

Use: **index_select()**

In [0]:
x = torch.randn(4,5)
print('\n------- x -------\n', x)

dim = 0
ind = torch.tensor([0,2])
y = torch.index_select(x, dim, ind)
print('\n------- y -------\n', y)

dim = 1
ind = torch.tensor([1,3])
z = torch.index_select(x, dim, ind)
print('\n------- z -------\n', z)


------- x -------
 tensor([[-0.7040,  1.6963, -0.4981,  0.9633, -0.0031],
        [ 0.1163,  0.3389, -1.7371, -1.7090,  0.7940],
        [ 0.5752, -0.3172,  0.6795, -0.6698,  0.6803],
        [-0.1180, -0.3273,  1.1346, -1.4317, -0.6906]])

------- y -------
 tensor([[-0.7040,  1.6963, -0.4981,  0.9633, -0.0031],
        [ 0.5752, -0.3172,  0.6795, -0.6698,  0.6803]])

------- z -------
 tensor([[ 1.6963,  0.9633],
        [ 0.3389, -1.7090],
        [-0.3172, -0.6698],
        [-0.3273, -1.4317]])


Narrowing Tensors.

Use: **narrow()** 

This returns a narrowed version of input tensor. The returned tensor and input tensor share the same underlying storage.

In [0]:
x = torch.tensor([[1, 3, 5], [2, 4, 6], [7, 9, 11]])

# Dimension 0, starting dimension 0, distance to the ending dimension 2
y = torch.narrow(x, 0, 0, 2)
print('\n------- y -------\n', y)

# Dimension 1, starting dimension 0, distance to the ending dimension 2
z = torch.narrow(x, 1, 0, 2)
print('\n------- z -------\n', z)

# Dimension 1, starting dimension 0, distance to the ending dimension 0
w = torch.narrow(x, 1, 0, 0)
print('\n------- w -------\n', w)

# Dimension 1, starting dimension 0, distance to the ending dimension 1
m = torch.narrow(x, 1, 0, 1)
print('\n------- w -------\n', m)


------- y -------
 tensor([[1, 3, 5],
        [2, 4, 6]])

------- z -------
 tensor([[1, 3],
        [2, 4],
        [7, 9]])

------- w -------
 tensor([], size=(3, 0), dtype=torch.int64)

------- w -------
 tensor([[1],
        [2],
        [7]])


To get a new tensor with the elements of *input* at the given indices use **take()**

In [0]:
x = torch.randn(3,4)
print('\n------- x -------\n', x)

y = torch.take(x, torch.tensor([0, 2, 4]))
print('\n------- y -------\n', y)


------- x -------
 tensor([[ 0.1329, -0.5227,  1.5469, -0.0512],
        [ 0.0728,  0.3324,  0.3946,  0.9631],
        [ 0.8221,  0.6847, -0.6631,  1.3371]])

------- y -------
 tensor([0.1329, 1.5469, 0.0728])


Transposing

Use: **transpose()**

This returns a tensor which is transposed version of input. The returned tensor and input tensor share the same underlying storage.

In [0]:
x = torch.randn(3,4)
print('\n --------- x -----------\n', x)

#swap dimension 1 with 0
y = torch.transpose(x, 1, 0)
print('\n --------- y -----------\n', y)

#swap dimension 0 with 1
z = torch.transpose(x, 0, 1)
print('\n --------- z -----------\n', z)


 --------- x -----------
 tensor([[ 1.6341,  1.1562, -0.7970, -0.2161],
        [-1.3215,  2.4176,  0.7607,  1.7081],
        [ 0.3304,  1.8977, -1.3115, -0.1656]])

 --------- y -----------
 tensor([[ 1.6341, -1.3215,  0.3304],
        [ 1.1562,  2.4176,  1.8977],
        [-0.7970,  0.7607, -1.3115],
        [-0.2161,  1.7081, -0.1656]])

 --------- z -----------
 tensor([[ 1.6341, -1.3215,  0.3304],
        [ 1.1562,  2.4176,  1.8977],
        [-0.7970,  0.7607, -1.3115],
        [-0.2161,  1.7081, -0.1656]])


Removing a tensor dimension

Use: **unbind()**
Returns a tuple of all slices along a given dimension.

In [0]:
x = torch.randn(3,3)
print('\n--------- x ----------\n',x)

#remove dimension 0
y = torch.unbind(x, 0)
print('\n--------- y ----------\n',y)

#remove dimension 1
z = torch.unbind(x, 1)
print('\n--------- z ----------\n',z)


--------- x ----------
 tensor([[ 0.1861, -1.0020, -1.1445],
        [-0.9733, -0.0657, -1.4559],
        [ 2.0416,  0.1199, -0.7548]])

--------- y ----------
 (tensor([ 0.1861, -1.0020, -1.1445]), tensor([-0.9733, -0.0657, -1.4559]), tensor([ 2.0416,  0.1199, -0.7548]))

--------- z ----------
 (tensor([ 0.1861, -0.9733,  2.0416]), tensor([-1.0020, -0.0657,  0.1199]), tensor([-1.1445, -1.4559, -0.7548]))


To get a new tensor with a dimension of size one inserted at specific position, use **unsqueeze()**

A dimension value *dim* within the range [-m-1, m+1] can be used, where m = input.dim()

*dim* is the index at which to insert singleton dimension

Negative value of *dim* will correspond to unsqueeze() applied at *dim = dim + m + 1*

Returned tensor shares the same underlying data

In [0]:
x = torch.tensor([2, 4, 6, 8, 10])
print('\n--------- x ----------\n',x)

#unsqueeze at index 0
y = torch.unsqueeze(x, 0)
#observe an extra pair of [] in y
print('\n--------- y ----------\n',y)

z = torch.unsqueeze(x, -1)
print('\n--------- z ----------\n',z)


--------- x ----------
 tensor([ 2,  4,  6,  8, 10])

--------- y ----------
 tensor([[ 2,  4,  6,  8, 10]])

--------- z ----------
 tensor([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])


Where condition in Tensors

Use: **where()**

Returns a tensor of elements selected from *x* or *y*, depending on given *condition*  

In [6]:
x = torch.randn(3,3)
y = torch.ones(3,3)

print('\n -------- x ---------\n', x)
print('\n -------- y ---------\n', y)

z = torch.where(x>1, x, y)
print('\n -------- z ---------\n', z)
#Observe in 'z' ---> wherever values of x>1, 'z' has those values from 'x', 
#otherwise z has values from 'y'


 -------- x ---------
 tensor([[-1.6161,  0.4550,  1.1773],
        [ 0.3256,  0.6040, -1.4305],
        [-0.0673,  0.5860,  0.8767]])

 -------- y ---------
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

 -------- z ---------
 tensor([[1.0000, 1.0000, 1.1773],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])
